# Cloud Build configuration for Alkanes
# Triggers on push to main branch

substitutions:
  _REGION: us-central1
  _SERVICE_NAME: alkanes-docs
  _SQL_INSTANCE: alkanes-postgres
  _REDIS_INSTANCE: alkanes-redis
  _VPC_CONNECTOR: alkanes-connector

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/alkanes-docker/${_SERVICE_NAME}:${COMMIT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/alkanes-docker/${_SERVICE_NAME}:latest'
      - '.'
    timeout: '1200s'

  # Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/alkanes-docker/${_SERVICE_NAME}'

  # Run database migrations
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Run migration job (DATABASE_URL is configured as a secret in the job)
        gcloud run jobs execute prisma-migrate \
          --region=${_REGION} \
          --wait \
        || echo "Migration job not found or failed, continuing..."

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Get connection info
        SQL_CONNECTION=$(gcloud sql instances describe ${_SQL_INSTANCE} --format='value(connectionName)')
        REDIS_IP=$(gcloud redis instances describe ${_REDIS_INSTANCE} --region=${_REGION} --format='value(host)')

        # Deploy (DATABASE_URL is already configured as a secret reference)
        gcloud run deploy ${_SERVICE_NAME} \
          --image ${_REGION}-docker.pkg.dev/${PROJECT_ID}/alkanes-docker/${_SERVICE_NAME}:${COMMIT_SHA} \
          --platform managed \
          --region ${_REGION} \
          --allow-unauthenticated \
          --port 3000 \
          --cpu 1 \
          --memory 512Mi \
          --min-instances 0 \
          --max-instances 10 \
          --concurrency 80 \
          --timeout 60 \
          --vpc-connector ${_VPC_CONNECTOR} \
          --add-cloudsql-instances "$${SQL_CONNECTION}" \
          --set-env-vars "NODE_ENV=production" \
          --set-env-vars "NEXT_PUBLIC_NETWORK=mainnet" \
          --set-env-vars "REDIS_URL=redis://$${REDIS_IP}:6379" \
          --set-secrets "DATABASE_URL=db-connection-string:latest"

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/alkanes-docker/${_SERVICE_NAME}:${COMMIT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/alkanes-docker/${_SERVICE_NAME}:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '1800s'
